// app/layout.js
import "./globals.css";
import localFont from "next/font/local";
import { SiteSettingsProviderWrapper } from "./SiteSettingsProviderWrapper"; // client wrapper
import { getSiteSettings } from "./lib/siteSettings"; // server-side fetch

const geistSans = localFont({ src: "./fonts/GeistVF.woff", variable: "--font-geist-sans", weight: "100 900" });
const geistMono = localFont({ src: "./fonts/GeistMonoVF.woff", variable: "--font-geist-mono", weight: "100 900" });

export default async function RootLayout({ children }) {
  // Server-side fetch
  const siteSettings = await getSiteSettings();
  const title = siteSettings?.name ?? "Lumina Blue";
  const bannerImg = siteSettings?.banners?.[0]?.bannerImg ?? "/default-banner.png";

  return (
    <html lang="en">
      <head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content={title} />
        <meta property="og:description" content="Generated by create next app" />
        <meta property="og:image" content={bannerImg} />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen w-full`}>
        {/* Client-side provider for interactivity */}
        <SiteSettingsProviderWrapper>
          {children}
        </SiteSettingsProviderWrapper>
      </body>
    </html>
  );
}
