import localFont from "next/font/local";
import "./globals.css";
import { getSiteSettings } from "./siteSettingsServer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export async function generateMetadata({ params }) {
  const practiceId = params.practiceId || null;
  const customerCode = params.customerCode || null;

  const { siteSettings } = await getSiteSettings(practiceId, customerCode);

  const title = siteSettings?.name || "Lumina Blue";
  const description = siteSettings?.aboutText || "Generated by create next app";
  const canonicalUrl = `https://lumina-blue-master.vercel.app/${practiceId || ""}`;
  const ogImageUrl = siteSettings?.banners?.[0]?.bannerImg || "/default-og-image.jpg";

  return {
    title,
    description,
    alternates: {
      canonical: canonicalUrl,
    },
    openGraph: {
      type: "website",
      url: canonicalUrl,
      title,
      description,
      images: [{ url: ogImageUrl }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [ogImageUrl],
    },
  };
}

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen w-full`}>
        <main className="flex-grow w-full relative">
          {children}
        </main>
      </body>
    </html>
  );
}
