import localFont from "next/font/local";
import "./globals.css";
import { getSiteSettings } from "./siteSettingsServer"; // Adjust if needed

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default async function RootLayout({ children, params }) {
  const practiceId = params?.practiceId || "";
  const customerCode = params?.customerCode || "";

  // Safely fetch settings — never throw during build
  let siteSettings = null;
  let error = null;

  try {
    const result = await getSiteSettings(practiceId, customerCode);
    siteSettings = result?.siteSettings ?? null;
  } catch (err) {
    error = err;
  }

  // Fallback defaults
  const title = siteSettings?.name || "Lumina Blue";
  const description = siteSettings?.aboutText || "Generated by create next app";
  const canonicalUrl = `https://lumina-blue-master.vercel.app/${practiceId}`;
  const ogImageUrl = siteSettings?.banners?.[0]?.bannerImg || "/default-og-image.jpg";
  const primaryColor = siteSettings?.primaryColor || "#1a1a1a";

  return (
    <html lang="en">
      <head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <link rel="canonical" href={canonicalUrl} />

        {/* Open Graph */}
        <meta property="og:type" content="website" />
        <meta property="og:url" content={canonicalUrl} />
        <meta property="og:title" content={title} />
        <meta property="og:description" content={description} />
        <meta property="og:image" content={ogImageUrl} />

        {/* Twitter */}
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content={canonicalUrl} />
        <meta property="twitter:title" content={title} />
        <meta property="twitter:description" content={description} />
        <meta property="twitter:image" content={ogImageUrl} />

        {/* Dynamic primary color */}
        <style
          dangerouslySetInnerHTML={{
            __html: `:root { --primary-color: ${primaryColor}; }`,
          }}
        />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen w-full`}>
        <main className="flex-grow w-full relative">
          {children}
        </main>
      </body>
    </html>
  );
}
