import localFont from "next/font/local";
import "./globals.css";
import { getSiteSettings } from './siteSettingsServer'; // Adjust the import path as needed

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Define a type for the RootLayout props to include params
export default async function RootLayout({
  children,
  params,
}) {
  const practiceId = params.practiceId || null; // Assuming practiceId comes from dynamic routes
  const customerCode = params.customerCode || null; // Assuming customerCode comes from dynamic routes

  const { siteSettings, error, isLoading } = await getSiteSettings(practiceId, customerCode);

  const title = siteSettings?.name || "Lumina Blue";
  const description = siteSettings?.aboutText || "Generated by create next app";
  const canonicalUrl = `https://www.example.com/${practiceId || ''}`; // Dynamically generate canonical URL

  // Find the first banner image, if available
  const ogImageUrl = siteSettings?.banners?.[0]?.bannerImg || "/default-og-image.jpg"; // Fallback to a default image

  return (
    <html lang="en">
      <head>
        <title>{isLoading ? "Loading..." : title}</title>
        <meta name="description" content={description} />
        <link rel="canonical" href={canonicalUrl} />
        {/* Open Graph / Facebook */}
        <meta property="og:type" content="website" />
        <meta property="og:url" content={canonicalUrl} />
        <meta property="og:title" content={title} />
        <meta property="og:description" content={description} />
        {ogImageUrl && <meta property="og:image" content={ogImageUrl} />} {/* Dynamic OG Image */}
        {/* Add more Open Graph tags if you have other data */}

        {/* Twitter */}
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content={canonicalUrl} />
        <meta property="twitter:title" content={title} />
        <meta property="twitter:description" content={description} />
        {ogImageUrl && <meta property="twitter:image" content={ogImageUrl} />} {/* Dynamic Twitter Image */}

        {/* Potentially add dynamic primary color variable here if needed for initial load */}
        {siteSettings?.primaryColor && (
          <style dangerouslySetInnerHTML={{ __html: `:root { --primary-color: ${siteSettings.primaryColor}; }` }} />
        )}
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen w-full`}>
        <main className="flex-grow w-full relative">
          {children}
        </main>
      </body>
    </html>
  );
}